variables:
  IMAGE_TAG: "$CI_PROJECT_PATH_SLUG:latest"
  SERVICE_NAME: "bilibili-web-player"
  REVIEW_URL: "https://bilibili-web-player.lanhcit.win/"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker service rm $SERVICE_NAME || true
    - docker service create
      --name $SERVICE_NAME
      --network backyard
      $IMAGE_TAG
  environment:
    name: staging
    url: $REVIEW_URL
  only:
    - master
